name: Deneme123

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cdcr.dev/cordatus-actions/gitact:github-actions
    - name: Login to Private Reg
      run: docker login cdcr.dev --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Private reg
      run: docker push cdcr.dev/cordatus-actions/gitact:github-actions
