name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build . --file Dockerfile --tag cdcr.dev/cordatus-actions/gitact:github-actions
    - name: Push to Private Reg
      run: docker login cdcr.dev --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker push cdcr.dev/cordatus-actions/gitact:github-actions
